apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: library-service-ingress
  namespace: library-service
spec:
  rules:
  - host: library-service.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: library-service
            port:
              number: 80

